### ISSUE TITLE
JDownloader doesn't start because the /tmp folder is missing

### ISSUE THREAD

**Issue by cremor** [PlusMinus0/headless-jd2-docker#31]
Since an JDownloader update on 29th or 30th of November it won't start any more with your Docker image (at least not with the latest tag, so Debian). Even recreating the container from scratch doesn't fix it. The problem is that JDownloader needs a /tmp folder, but you remove that folder with the command `rm -rf tmp` in the Dockerfile.
I suggest to just clear the /tmp folder instead of completely removing it.

This is the exception from JDownloader:
```
SysProp: java.io.tmpdir: /tmp
java.io.IOException: No such file or directory
--ID:27TS:1543853407852-12/3/18, 5:10:07 PM - [org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString)] -> at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
--ID:27TS:1543853407852-12/3/18, 5:10:07 PM - [org.appwork.utils.logging2.InputStreamLogger(readInputStreamToString)] -> at java.base/java.io.File.createTempFile(File.java:2090)
```

Btw, this not only affects JDownloader, but also other things, e.g. apt-get. I can't even run `apt-get update` when there is no /tmp folder. (I needed this when I tried to debug the JDownloader startup bug.)

**Comment by cremor** [comment]
FYI: This might soon not be a problem any more because the JDownloader devs said they would make sure that JDownloader can start without a /tmp folder. But I still suggest to change it in the Docker image.
